[tool.poetry]
name = "oceanproc"
version = "0.1.0"
description = "MRI preprocessing for WUSTL Ocean labs"
authors = ["Ramone Agard <agardr@wustl.edu>", "Joey Scanga <joeyscanga92@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.2"

[tool.poetry.scripts]
oceanproc = "oceanproc.ocean_proc:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
