[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ocean-proc"
version = "0.0.1"
requires-python = " >= 3.9 " 
dependencies = [
	"alabaster==0.7.16",
	"Babel==2.15.0",
	"certifi==2024.2.2",
	"charset-normalizer==3.3.2",
	"docutils==0.21.2",
	"exceptiongroup==1.2.1",
	"idna==3.7",
	"imagesize==1.4.1",
	"iniconfig==2.0.0",
	"Jinja2==3.1.4",
	"MarkupSafe==2.1.5",
	"packaging==24.0",
	"pluggy==1.5.0",
	"Pygments==2.18.0",
	"pytest==8.2.0",
	"requests==2.32.2",
	"snowballstemmer==2.2.0",
	"Sphinx==7.3.7",
	"sphinxcontrib-applehelp==1.0.8",
	"sphinxcontrib-devhelp==1.0.6",
	"sphinxcontrib-htmlhelp==2.0.5",
	"sphinxcontrib-jsmath==1.0.1",
	"sphinxcontrib-qthelp==1.0.7",
	"sphinxcontrib-serializinghtml==1.1.10",
	"tomli==2.0.1",
	"urllib3==2.2.1",
]
readme = "README.md"
classifiers = [
	"Development Status :: 2 - Pre-Alpha",
	"Environment :: Console",
	"Intended Audience :: Science/Research",
	"Operating System :: POSIX :: Linux",
]


